export const STREET_TYPES: Array<string> = [
	'Alley',
	'Street',
	'Avenue',
	'Broad',
	'Brick Road',
	'Boulevard',
	'Bundesstraße',
	'Byway',
	'Causeway',
	'Circle',
	'Collector road',
	'Corniche',
	'Close',
	'Crescent',
	'Court',
	'Cul-de-sac / Dead end (street)',
	'Drive',
	'Frontage road',
	'Gemeindestraße',
	'Highway',
	'Kreisstraße',
	'Lane',
	'Landesstraße',
	'Living street',
	'Loop',
	'One-way street',
	'Path',
	'Place',
	'Plaza',
	'Road',
	'Roundabout (Also see intersecting roadways)',
	'Route',
	'Side road',
	'Single carriageway',
	'Stravenue',
	'Terrace',
	'Way',
	'Tree Tunnel',
	'Woonerf',
];
